name: Simple ci build
on:
  push:
    branch:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest    
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - uses: ./.github/workflows/build.yml    
    